name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-14
    
    strategy:
      matrix:
        xcode: ['15.0']
        ios: ['17.0']
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: Show Swift version
      run: swift --version
      
    - name: Cache Swift Package Dependencies
      uses: actions/cache@v3
      with:
        path: |
          .build
        key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    - name: Build
      run: swift build
    
    - name: Run tests
      run: swift test
      
    - name: Build for iOS Simulator
      run: |
        xcodebuild -scheme SkyColor \
          -destination "platform=iOS Simulator,name=iPhone 15,OS=${{ matrix.ios }}" \
          -configuration Release \
          build-for-testing
          
    - name: Build for macOS
      run: |
        xcodebuild -scheme SkyColor \
          -destination "platform=macOS" \
          -configuration Release \
          build

  documentation:
    runs-on: macos-14
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer
      
    - name: Build Documentation
      run: |
        swift package generate-documentation \
          --target SkyColor \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path SkyColor \
          --output-path ./docs
          
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
